# Generated by Django 4.0.3 on 2022-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ratings',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good'), ('5', 'perfect')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=99),
        ),
    ]
