# Generated by Django 4.0.3 on 2022-07-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_ratings_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer']},
        ),
    ]
