# Generated by Django 4.0.3 on 2022-04-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_remove_cart_merchant_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('products', models.ManyToManyField(blank=True, null=True, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.merchant'),
        ),
    ]
