# Generated by Django 4.0.3 on 2022-05-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_merchant_order_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
