# Generated by Django 4.0.3 on 2022-07-06 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ratings',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('very bad', 'very bad'), ('bad', 'bad'), ('good', 'good'), ('very good', 'very good'), ('perfect', 'perfect')], default='1', max_length=50)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
