# Generated by Django 4.0.3 on 2022-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_order_ratings_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
