# Generated by Django 4.0.3 on 2022-05-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cart_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='available',
            new_name='occupied',
        ),
    ]
