# Generated by Django 4.0.3 on 2022-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usedtransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField(default=0, null=True)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=10000, max_digits=99),
        ),
    ]
