# Generated by Django 4.0.3 on 2022-05-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_bar_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bar_code',
            new_name='barcode',
        ),
    ]
