# Generated by Django 4.0.3 on 2022-05-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_orderitem_order_orderitem_orderitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderItems',
            new_name='order',
        ),
    ]
